### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by geekoide** [telcy/business-directory-template-laravel#1]
Hello, 
I can not find the view of the company record (frontend/listing).
Thank you

**Comment by telcy** [comment]
Thanks for reporting. I have added the files in https://github.com/telcy/business-directory-template-laravel/commit/4ab3ec08a16ff77d0bbbc5d02ddf57713e85da3f

**Comment by geekoide** [comment]
it also misses the view files in the backend/listing directory
Thank
